Add support for environment variable TARANTOOL_REGISTRY
tarantool/testcontainers-java-tarantool pull request #124
Opened 2024-05-03 16:44 UTC by vasilevichra

I haven't forgotten about:
- [ ] Tests
- [ ] Changelog
- [ ] Documentation
- [ ] Commit messages comply with the [guideline](https://www.tarantool.io/en/doc/latest/dev_guide/developer_guidelines/#how-to-write-a-commit-message)
- [ ] Cleanup the code for review. See [checklist](https://github.com/tarantool/cartridge-java/blob/master/docs/review-checklist.md)

Related issues:

2024-05-06 07:34 UTC, ArtDu commented on .github/workflows/tests.yml
> +
тут принт имаджей не добавил

2024-05-06 07:34 UTC, ArtDu commented on CHANGELOG.md
> +## [1.3.3] - 2024-05-03
```suggestion
## [1.3.3] - 2024-05-06
```

2024-05-06 07:34 UTC, ArtDu commented on src/main/java/org/testcontainers/containers/TarantoolImageParams.java
> +    public TarantoolImageParams(String tag, File dockerfile, String defaultImage) {
Так кажется понятнее

```suggestion
    public TarantoolImageParams(String tag, File dockerfile, String baseImageName) {
```

2024-05-06 07:41 UTC, dkasimovskiy requested changes

2024-05-06 07:41 UTC, dkasimovskiy commented on pom.xml
> +                        <TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX>${env.TARANTOOL_REGISTRY}</TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX>
Название тега должно быть в camelCase

2024-05-06 07:41 UTC, dkasimovskiy commented on pom.xml
> +                                <TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX>${env.TARANTOOL_REGISTRY}</TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX>
то же самое

2024-05-06 07:41 UTC, dkasimovskiy commented on pom.xml
> +                                <TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX>${env.TARANTOOL_REGISTRY}</TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX>
то же самое

2024-05-06 07:41 UTC, dkasimovskiy commented on src/main/resources/Dockerfile
> +ARG IMAGE="tarantool/tarantool:$TARANTOOL_VERSION"
IMAGE_NAME выглядит более правильным названием

2024-05-06 12:10 UTC, ArtDu reviewed
Не понятно откуда только эти имаджы. Как зависимость от главных? почему они без registry тогда странно

![image](https://github.com/tarantool/testcontainers-java-tarantool/assets/22258443/41718f64-a665-4089-9e51-2bed64c33fd7)

2024-05-06 12:10 UTC, ArtDu commented on src/main/java/org/testcontainers/containers/TarantoolContainer.java
> +                    (registry.endsWith("/") ? registry + DEFAULT_IMAGE_NAME : registry + "/" + DEFAULT_IMAGE_NAME);
Этот код можно вынести. Он такой же в `TarantoolImageParams#extract`

2024-05-06 12:19 UTC, dkasimovskiy requested changes

2024-05-06 12:19 UTC, dkasimovskiy commented on src/main/resources/Dockerfile
> +ARG IMAGE_NAME="tarantool/tarantool:$TARANTOOL_VERSION"
```suggestion
ARG IMAGE="tarantool/tarantool"
```

2024-05-06 12:19 UTC, dkasimovskiy commented on src/main/resources/Dockerfile
> +FROM $IMAGE_NAME AS cartridge-base
```suggestion
FROM {$IMAGE}:${TARANTOOL_VERSION} AS cartridge-base
```

2024-05-06 12:19 UTC, dkasimovskiy commented on src/main/java/org/testcontainers/containers/TarantoolContainer.java
> +    public static final String DEFAULT_IMAGE_NAME = "tarantool/tarantool";
```suggestion
    public static final String DEFAULT_IMAGE = "tarantool/tarantool";
```

2024-05-06 12:19 UTC, dkasimovskiy commented on src/main/java/org/testcontainers/containers/TarantoolContainer.java
>      public static final String DEFAULT_IMAGE_VERSION = "2.11.2-ubuntu20.04";
```suggestion
    public static final String DEFAULT_TAG = "2.11.2-ubuntu20.04";
```

Если следовать именованию в https://docs.docker.com/reference/dockerfile/#from

2024-05-06 12:19 UTC, dkasimovskiy commented on src/main/java/org/testcontainers/containers/TarantoolContainer.java
> +    public static final String DEFAULT_BASE_IMAGE = String.format("%s:%s", DEFAULT_IMAGE_NAME, DEFAULT_IMAGE_VERSION);
```suggestion
    public static final String DEFAULT_BASE_IMAGE = String.format("%s:%s", DEFAULT_IMAGE, DEFAULT_TAG);
```

2024-05-06 13:00 UTC, vasilevichra commented on src/test/java/org/testcontainers/containers/TarantoolCartridgeBootstrapFromLuaWithFixedPortsIT.java
> +                    System.getenv().getOrDefault("TESTCONTAINERS_HUB_IMAGE_NAME_PREFIX", "") + "cartridge",
Все образы ищутся по пути в переменной. Без этого не работает.

2024-05-06 13:08 UTC, vasilevichra commented on src/main/java/org/testcontainers/containers/TarantoolContainer.java
> +                    (registry.endsWith("/") ? registry + DEFAULT_IMAGE_NAME : registry + "/" + DEFAULT_IMAGE_NAME);
Ну такое. Там карта создаётся на 4 параметра и всё инкапсулировано, а тут работа с 2 переменными окружения. Из-за двух переменных городить целый публичный метод...

2024-05-06 13:59 UTC, vasilevichra commented on src/main/resources/Dockerfile
> +FROM $IMAGE_NAME AS cartridge-base
Это будет не единообразно для каких-нибудь centos:7

2024-05-06 14:22 UTC, dkasimovskiy commented on src/main/resources/Dockerfile
> +FROM $IMAGE_NAME AS cartridge-base
По-хорошему TARANTOOL_VERSION нужно переименовать в TAG или TAG_NAME, но это ломает обратную совместимость.
С другой стороны, переменная $IMAGE не должна содержать в себе TAG, если следовать документации [dockerfile](https://docs.docker.com/reference/dockerfile/#from)

2024-05-06 14:46 UTC, ArtDu commented
> > Не понятно откуда только эти имаджы. Как зависимость от главных? почему они без registry тогда странно
> > ![image](https://private-user-images.githubusercontent.com/22258443/328172160-41718f64-a665-4089-9e51-2bed64c33fd7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwMDA2NjQsIm5iZiI6MTcxNTAwMDM2NCwicGF0aCI6Ii8yMjI1ODQ0My8zMjgxNzIxNjAtNDE3MThmNjQtYTY2NS00MDg5LTllNTEtMmJlZDY0YzMzZmQ3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDEyNTkyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4Y2UwNjFhNjI1MjA4MTcxOTQ3MWEyZmI5YmZjNDEyYWVjZTEyYjhlNjAxZmJhYWJmMGQ1OTVmYmI4MjU2MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zhrQOTxxg6-Z6W_bMbZVJFWxzwYSlNY-yUf-FLC_9W0)
> 
> Ага, видел. Их базовые тянут откуда-то. Не нашёл способа, как на них можно повлиять. А может быть это какой-нибудь кэш.

Странно то, я сейчас загрузил все эти 3 имаджа, но другие нет когда вызываешь docker images. 

<img width="801" alt="image" src="https://github.com/tarantool/testcontainers-java-tarantool/assets/22258443/aaca1cc8-1359-4640-b19b-e416573bf958">

Может надо просто почистить лишнее? у тебя есть доступ до машинок, попробовать почистить и заново запустить CI?

2024-05-06 15:08 UTC, ArtDu reviewed
LGTM, только IMAGE надо, чтобы не затерал TARANTOOL_VERSION

2024-05-07 07:38 UTC, dkasimovskiy approved these changes

2024-05-07 08:57 UTC, ArtDu approved these changes

2024-05-07 10:15 UTC, merged